const dataGeo = [
  {
    ID: 7168958,
    Time: 1933,
    Person: true,
    Company: false,
    Name: 'Kurnz Henry M.',
    Occupation: 'Clerk',
    Address:
      '27 Bridge St., Manhattan, New York, Manhattan, New York, United States',
    Birthplace: 'United States',
    State: 'Massachusetts',
    Gender: 'Male',
    Age: 23,
    Immigration_year: 1931,
    Latitude: 40.70362002,
    Longitude: -74.01225536,
  },
  {
    ID: 7168959,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Lux J. B.',
    Occupation: 'Clerk',
    Address: '4 Union Square, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Russia',
    State: null,
    Gender: 'Male',
    Age: 34,
    Immigration_year: 1913,
    Latitude: 40.73555276,
    Longitude: -73.98981801,
  },
  {
    ID: 7168960,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'McCormick M. J.',
    Occupation: 'Police',
    Address: '475 4 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Norway',
    State: null,
    Gender: 'Female',
    Age: 45,
    Immigration_year: 1913,
    Latitude: 40.7455414,
    Longitude: -73.98270098,
  },
  {
    ID: 7168961,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'McDonald E. H.',
    Occupation: 'Clerk',
    Address: '380 W 125 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 19,
    Immigration_year: 1913,
    Latitude: 40.81042335,
    Longitude: -73.95178696,
  },
  {
    ID: 7168962,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'McKinley Square Casino',
    Occupation: null,
    Address: '775 E 169 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Ireland',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1918,
    Latitude: 40.7455414,
    Longitude: -73.98270098,
  },
  {
    ID: 7168963,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'Maison Chevalier',
    Occupation: null,
    Address: '141 Fulton St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'France',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1918,
    Latitude: 40.71136583,
    Longitude: -74.00895991,
  },
  {
    ID: 7168964,
    Time: 1920,
    Person: true,
    Company: false,
    Name: 'Hammer M.',
    Occupation: 'Laborer',
    Address: '204 9 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'New York',
    Gender: 'Female',
    Age: 23,
    Immigration_year: 1918,
    Latitude: 40.74624872,
    Longitude: -74.00152062,
  },
  {
    ID: 7168965,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'Madison Buffet Lunch',
    Occupation: null,
    Address: '145 Madison Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Iowa',
    Gender: null,
    Age: null,
    Immigration_year: 1918,
    Latitude: 40.74632028,
    Longitude: -73.98429964,
  },
  {
    ID: 7168966,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Rothman David',
    Occupation: 'Clerk',
    Address:
      '195 Bowery St., Manhattan, New York, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Hungary',
    State: null,
    Gender: 'Male',
    Age: 53,
    Immigration_year: 1908,
    Latitude: 40.72196146,
    Longitude: -73.99354518,
  },
  {
    ID: 7168967,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Maggi H.',
    Occupation: 'Laborer',
    Address: '103 W 38 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Germany',
    State: null,
    Gender: 'Female',
    Age: 27,
    Immigration_year: 1913,
    Latitude: 40.75272525,
    Longitude: -73.98645786,
  },
  {
    ID: 7168968,
    Time: 1910,
    Person: false,
    Company: true,
    Name: 'Rothstein & Davidowitz',
    Occupation: null,
    Address: '130 W 36 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Austria',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1908,
    Latitude: 40.75127316,
    Longitude: -73.98712193,
  },
  {
    ID: 7168969,
    Time: 1920,
    Person: false,
    Company: true,
    Name: "Mahnken's Lunch",
    Occupation: null,
    Address: '167 William St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Maine',
    Gender: null,
    Age: null,
    Immigration_year: 1918,
    Latitude: 40.71079921,
    Longitude: -74.00565377,
  },
  {
    ID: 7168970,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Heller & Heller',
    Occupation: null,
    Address: '528 7 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Austria',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
    Latitude: 40.75263949,
    Longitude: -73.98728316,
  },
  {
    ID: 7168971,
    Time: 1920,

    Person: true,
    Company: false,
    Name: 'Maloney J. J.',
    Occupation: 'Porter',
    Address: '791 7 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 50,
    Immigration_year: 1918,
    Latitude: 40.76204775,
    Longitude: -73.98263806,
  },
  {
    ID: 7168972,
    Time: 1920,
    Person: true,
    Company: false,

    Name: 'Mandl J.',
    Occupation: 'Laborer',
    Address: '31 W 26 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Hungary',
    State: null,
    Gender: 'Female',
    Age: 61,
    Immigration_year: 1918,
    Latitude: 40.74474498,
    Longitude: -73.99061178,
  },
  {
    ID: 7168973,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Rozumkiewicz Michael',
    Occupation: 'Waiter',
    Address: '1st Avenue, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Greece',
    State: null,
    Gender: 'Male',
    Age: 35,
    Immigration_year: 1908,
    Latitude: 40.72399929,
    Longitude: -73.98833764,
  },
  {
    ID: 7168974,
    Time: 1905,
    Person: false,
    Company: true,
    Name: 'Hip Chong Low',
    Occupation: null,
    Address: '203 W. 38 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'China',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1903,
    Latitude: 40.75438852,
    Longitude: -73.99057161,
  },
  {
    ID: 7168975,
    Time: 1905,
    Person: true,
    Company: false,
    Name: 'Jacovitz Reuben',
    Occupation: 'Clerk',
    Address: '77 Chrystie St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Romania',
    State: null,
    Gender: 'Male',
    Age: 65,
    Immigration_year: 1903,
    Latitude: 40.72162887,
    Longitude: -73.98308248,
  },
  {
    ID: 7168976,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Yamada J.',
    Occupation: 'Laborer',
    Address: '470 8 Ave, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Japan',
    State: null,
    Gender: 'Male',
    Age: 39,
    Immigration_year: 1908,
    Latitude: 40.75195525,
    Longitude: -73.99373048,
  },
  {
    ID: 7168977,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Maros & Terzoglos',
    Occupation: null,
    Address: '300 E 23 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Italy',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
    Latitude: 40.73764708,
    Longitude: -73.97999879,
  },
  {
    ID: 7168978,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Adams Rose R.',
    Occupation: 'Other',
    Address: '133 W 49 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Ohio',
    Gender: 'Female',
    Age: 69,
    Immigration_year: 1913,
    Latitude: 40.74644159,
    Longitude: -73.99779513,
  },
  {
    ID: 7168979,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Zilzer Harry',
    Occupation: 'Clerk',
    Address: '2130 Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 43,
    Immigration_year: 1908,
    Latitude: 40.77460271,
    Longitude: -73.95150371,
  },
  {
    ID: 7168980,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Elsinger Ralph',
    Occupation: 'Clerk',
    Address: '112 E. 23 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Canada',
    State: 'Nova Scotia',
    Gender: 'Male',
    Age: 62,
    Immigration_year: 1913,
    Latitude: 40.74024188,
    Longitude: -73.98620591,
  },
  {
    ID: 7168981,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Yan Kin',
    Occupation: 'Clerk',
    Address: '400 6 Ave, Manhattan, New York, Manhattan, New York',
    Birthplace: 'China',
    State: null,
    Gender: 'Male',
    Age: 73,
    Immigration_year: 1908,
    Latitude: 40.74420235,
    Longitude: -73.99210396,
  },
  {
    ID: 7168982,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Ferdinand & Littwin',
    Occupation: null,
    Address: '38 W. 20 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'North Carolina',
    Gender: null,
    Age: null,
    Immigration_year: 1913,
    Latitude: 40.73406286,
    Longitude: -73.9994535,
  },
  {
    ID: 7168983,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Gibson Restaurant Co.',
    Occupation: null,
    Address: '22 W 17 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Ireland',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
    Latitude: 40.70912133,
    Longitude: -74.00708915,
  },
  {
    ID: 7168984,
    Time: 1895,
    Person: true,
    Company: false,
    Name: 'Chacon Jase',
    Occupation: 'Porter',
    Address: '177 W Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'South America',
    State: null,
    Gender: 'Male',
    Age: 77,
    Immigration_year: 1893,
    Latitude: 40.7286446,
    Longitude: -73.99915458,
  },
  {
    ID: 7168985,
    Time: 1895,
    Person: true,
    Company: false,
    Name: 'Cohen Abraham',
    Occupation: 'Laborer',
    Address: '148  Delancey St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Russia',
    State: null,
    Gender: 'Male',
    Age: 51,
    Immigration_year: 1893,
    Latitude: 40.71971379,
    Longitude: -73.98142983,
  },
  {
    ID: 7168986,
    Time: 1895,
    Person: false,
    Company: true,
    Name: 'Delisle Brothers',
    Occupation: null,
    Address: '557 W Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'France',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1893,
    Latitude: 40.70980392,
    Longitude: -74.00599679,
  },
  {
    ID: 7168987,
    Time: 1925,
    Person: false,
    Company: true,
    Name: 'Kronenberg Inc.',
    Occupation: null,
    Address: '3550 Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Denmark',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1923,
    Latitude: 40.72075707,
    Longitude: -73.99948285,
  },
]

const dataNonGeo = [
  {
    ID: 7168958,
    Time: 1933,
    Person: true,
    Company: false,
    Name: 'Kurnz Henry M.',
    Occupation: 'Clerk',
    Address:
      '27 Bridge St., Manhattan, New York, Manhattan, New York, United States',
    Birthplace: 'United States',
    State: 'Massachusetts',
    Gender: 'Male',
    Age: 23,
    Immigration_year: 1931,
  },
  {
    ID: 7168959,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Lux J. B.',
    Occupation: 'Clerk',
    Address: '4 Union Square, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Russia',
    State: null,
    Gender: 'Male',
    Age: 34,
    Immigration_year: 1913,
  },
  {
    ID: 7168960,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'McCormick M. J.',
    Occupation: 'Police',
    Address: '475 4 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Norway',
    State: null,
    Gender: 'Female',
    Age: 45,
    Immigration_year: 1913,
  },
  {
    ID: 7168961,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'McDonald E. H.',
    Occupation: 'Clerk',
    Address: '380 W 125 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 19,
    Immigration_year: 1913,
  },
  {
    ID: 7168962,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'McKinley Square Casino',
    Occupation: null,
    Address: '775 E 169 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Ireland',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1918,
  },
  {
    ID: 7168963,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'Maison Chevalier',
    Occupation: null,
    Address: '141 Fulton St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'France',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1918,
  },
  {
    ID: 7168964,
    Time: 1920,
    Person: true,
    Company: false,
    Name: 'Hammer M.',
    Occupation: 'Laborer',
    Address: '204 9 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'New York',
    Gender: 'Female',
    Age: 23,
    Immigration_year: 1918,
  },
  {
    ID: 7168965,
    Time: 1920,
    Person: false,
    Company: true,
    Name: 'Madison Buffet Lunch',
    Occupation: null,
    Address: '145 Madison Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Iowa',
    Gender: null,
    Age: null,
    Immigration_year: 1918,
  },
  {
    ID: 7168966,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Rothman David',
    Occupation: 'Clerk',
    Address:
      '195 Bowery St., Manhattan, New York, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Hungary',
    State: null,
    Gender: 'Male',
    Age: 53,
    Immigration_year: 1908,
  },
  {
    ID: 7168967,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Maggi H.',
    Occupation: 'Laborer',
    Address: '103 W 38 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Germany',
    State: null,
    Gender: 'Female',
    Age: 27,
    Immigration_year: 1913,
  },
  {
    ID: 7168968,
    Time: 1910,
    Person: false,
    Company: true,
    Name: 'Rothstein & Davidowitz',
    Occupation: null,
    Address: '130 W 36 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Austria',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1908,
  },
  {
    ID: 7168969,
    Time: 1920,
    Person: false,
    Company: true,
    Name: "Mahnken's Lunch",
    Occupation: null,
    Address: '167 William St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Maine',
    Gender: null,
    Age: null,
    Immigration_year: 1918,
  },
  {
    ID: 7168970,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Heller & Heller',
    Occupation: null,
    Address: '528 7 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Austria',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
  },
  {
    ID: 7168971,
    Time: 1920,
    Person: true,
    Company: false,
    Name: 'Maloney J. J.',
    Occupation: 'Porter',
    Address: '791 7 Ave., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 50,
    Immigration_year: 1918,
  },
  {
    ID: 7168972,
    Time: 1920,
    Person: true,
    Company: false,
    Name: 'Mandl J.',
    Occupation: 'Laborer',
    Address: '31 W 26 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Hungary',
    State: null,
    Gender: 'Female',
    Age: 61,
    Immigration_year: 1918,
  },
  {
    ID: 7168973,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Rozumkiewicz Michael',
    Occupation: 'Waiter',
    Address: '1st Avenue, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Greece',
    State: null,
    Gender: 'Male',
    Age: 35,
    Immigration_year: 1908,
  },
  {
    ID: 7168974,
    Time: 1905,
    Person: false,
    Company: true,
    Name: 'Hip Chong Low',
    Occupation: null,
    Address: '203 W. 38 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'China',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1903,
  },
  {
    ID: 7168975,
    Time: 1905,
    Person: true,
    Company: false,
    Name: 'Jacovitz Reuben',
    Occupation: 'Clerk',
    Address: '77 Chrystie St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Romania',
    State: null,
    Gender: 'Male',
    Age: 65,
    Immigration_year: 1903,
  },
  {
    ID: 7168976,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Yamada J.',
    Occupation: 'Laborer',
    Address: '470 8 Ave, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Japan',
    State: null,
    Gender: 'Male',
    Age: 39,
    Immigration_year: 1908,
  },
  {
    ID: 7168977,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Maros & Terzoglos',
    Occupation: null,
    Address: '300 E 23 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Italy',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
  },
  {
    ID: 7168978,
    Time: 1915,
    Person: true,
    Company: false,
    Name: 'Adams Rose R.',
    Occupation: 'Other',
    Address: '133 W 49 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'Ohio',
    Gender: 'Female',
    Age: 69,
    Immigration_year: 1913,
  },
  {
    ID: 7168979,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Zilzer Harry',
    Occupation: 'Clerk',
    Address: '2130 Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'United Kingdom',
    State: null,
    Gender: 'Male',
    Age: 43,
    Immigration_year: 1908,
  },
  {
    ID: 7168980,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Elsinger Ralph',
    Occupation: 'Clerk',
    Address: '112 E. 23 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Canada',
    State: 'Nova Scotia',
    Gender: 'Male',
    Age: 62,
    Immigration_year: 1913,
  },
  {
    ID: 7168981,
    Time: 1910,
    Person: true,
    Company: false,
    Name: 'Yan Kin',
    Occupation: 'Clerk',
    Address: '400 6 Ave, Manhattan, New York, Manhattan, New York',
    Birthplace: 'China',
    State: null,
    Gender: 'Male',
    Age: 73,
    Immigration_year: 1908,
  },
  {
    ID: 7168982,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Ferdinand & Littwin',
    Occupation: null,
    Address: '38 W. 20 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'United States',
    State: 'North Carolina',
    Gender: null,
    Age: null,
    Immigration_year: 1913,
  },
  {
    ID: 7168983,
    Time: 1915,
    Person: false,
    Company: true,
    Name: 'Gibson Restaurant Co.',
    Occupation: null,
    Address: '22 W 17 St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Ireland',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1913,
  },
  {
    ID: 7168984,
    Time: 1895,
    Person: true,
    Company: false,
    Name: 'Chacon Jase',
    Occupation: 'Porter',
    Address: '177 W Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'South America',
    State: null,
    Gender: 'Male',
    Age: 77,
    Immigration_year: 1893,
  },
  {
    ID: 7168985,
    Time: 1895,
    Person: true,
    Company: false,
    Name: 'Cohen Abraham',
    Occupation: 'Laborer',
    Address: '148  Delancey St., Manhattan, New York, Manhattan, New York',
    Birthplace: 'Russia',
    State: null,
    Gender: 'Male',
    Age: 51,
    Immigration_year: 1893,
  },
  {
    ID: 7168986,
    Time: 1895,
    Person: false,
    Company: true,
    Name: 'Delisle Brothers',
    Occupation: null,
    Address: '557 W Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'France',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1893,
  },
  {
    ID: 7168987,
    Time: 1925,
    Person: false,
    Company: true,
    Name: 'Kronenberg Inc.',
    Occupation: null,
    Address: '3550 Broadway, Manhattan, New York, Manhattan, New York',
    Birthplace: 'Denmark',
    State: null,
    Gender: null,
    Age: null,
    Immigration_year: 1923,
  },
]

export { dataGeo, dataNonGeo }
